apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2  # You can adjust the number of replicas
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: baishla123/app-raghav-backend-image:latest  # Image from Docker Hub
        ports:
        - containerPort: 3001
        env: 
        - name: MONGO_URI
          value: "mongodb://mongoUser:Password@mongo:27017/my-database"

