apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Matches the label in the Deployment
  ports:
    - protocol: TCP
      port: 8080          # External port to access the service
      targetPort: 3001    # Port on the backend container
  type: NodePort         # Internal communication within the cluster

